name = "Laurence Create"
author = "Meeeee"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a69949f0d833a0c5166801535b6028acc24264f793c8f55a77997c8698cfe492"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
