name = "Laurence Create"
author = "Meeeee"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ff7f9ae68df91744a579e5c4af23cb0cb2da742510b9e2f7a115fb21a6945cd"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
