name = "Laurence Create"
author = "Meeeee"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dde295381e5af6fe0f23ee381751f856844919f820a2b24ebc1a33a033ec78ae"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
