name = "Laurence Create"
author = "Meeeee"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6aec864884418df03b798ef6b26f5cb0fa5b93f82188f9db2f369787fc173dd5"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
