name = "Laurence Create"
author = "Meeeee"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61654fac112f4e79e068976eafdfb78a6f48e4d0c0b0af43c4ecb2c4a301f13b"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
