name = "Laurence Create"
author = "Meeeee"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09b90ef62174cffa38601913ae218bb233643bb821a30b56d37d0f6297b62316"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
