name = "Laurence Create"
author = "Meeeee"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b2efc46a25fc0a3aa9de626874f740e1f7c127e25edd15fd317f5dc8f9c88dd"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
