name = "Laurence Create"
author = "Meeeee"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "883da759db53fd994ac51782fbc8cbb3722216bc504d2ca8bbea9b7e22ce17c4"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
